language: go

sudo: false

matrix:
  include:
  - os: linux
    go: "1.9.x"
  - os: windows
    go: "1.9.x"
  - os: linux
    go: "1.10.x"
  - os: windows
    go: "1.10.x"
  - os: linux
    go: "1.11.x"
    env:
      - GO111MODULE=off
  - os: windows
    go: "1.11.x"
    env:
      - GO111MODULE=off
  - os: linux
    go: "1.11.x"
    env:
      - GO111MODULE=on
  - os: windows
    go: "1.11.x"
    env:
      - GO111MODULE=on

install: false

script: 
  - go get -v -tags ${TAGS} -t ./...
  - go test -v -tags ${TAGS} -timeout=5s -race ./...
